version: "3.9"

services:
  gobox-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gobox-app
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gobox-network
    env_file:
      - .env
    depends_on:
      gobox-postgres:
        condition: service_healthy

  gobox-postgres:
    image: postgres:latest
    container_name: gobox-postgres
    restart: always
    environment:
      POSTGRES_USER: gobox
      POSTGRES_PASSWORD: gobox123
      POSTGRES_DB: gobox
    ports:
      - "5432:5432"
    volumes:
      - gobox_pgdata:/var/lib/postgresql/data
    networks:
      - gobox-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gobox -d gobox"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  gobox_pgdata:

networks:
  gobox-network:
    driver: bridge
