services:
  app:
    image: ghcr.io/faiyaz032/gobox:main
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: gobox-prod
    restart: always
    ports:
      - "${SERVER_PORT:-8010}:8010"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - gobox-network

  postgres:
    image: postgres
    container_name: gobox-postgres-prod
    restart: always
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT:-5435}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gobox-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-gobox} -d $${POSTGRES_DB:-goboxdb}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  gobox-network:
    driver: bridge
